sonar.projectKey=ecommerce-microservices
sonar.projectName=E-Commerce Microservices
sonar.sources=.
# Exclude Kubernetes manifests and GitHub Action configurations from being scanned as code
sonar.exclusions=**/*.yaml,**/*.yml,kubernetes/**

# If you are using SonarCloud instead of a self-hosted SonarQube, uncomment the line below and add your organization name:
# sonar.organization=your_organization_name
