FROM node:20-alpine
RUN apk update && apk upgrade --no-cache
WORKDIR /app
COPY package*.json ./
RUN npm install --production
COPY . .
EXPOSE 3013
HEALTHCHECK --interval=30s --timeout=3s CMD wget -qO- http://localhost:3013/health || exit 1
CMD ["node", "src/index.js"]
