adminService:
  image:
    repository: team4devops/ecommerce-admin-service
    tag: v1.0.0
  replicas: 1
apiGateway:
  image:
    repository: team4devops/ecommerce-api-gateway
    tag: v1.0.0
  replicas: 2
authService:
  image:
    repository: team4devops/ecommerce-authentication-service
    tag: v1.0.0
  replicas: 2
cartService:
  image:
    repository: team4devops/ecommerce-cart-service
    tag: v1.0.0
  replicas: 1
frontendUi:
  image:
    repository: team4devops/ecommerce-frontend-ui
    tag: v1.0.0
  replicas: 2
inventoryService:
  image:
    repository: team4devops/ecommerce-inventory-service
    tag: v1.0.0
  replicas: 1
invoiceService:
  image:
    repository: team4devops/ecommerce-invoice-service
    tag: v1.0.0
  replicas: 1
mongodb:
  image:
    repository: mongo
    tag: '6.0'
  replicas: 1
namespace: clahanstore
orderService:
  image:
    repository: team4devops/ecommerce-order-service
    tag: v1.0.0
  replicas: 1
paymentService:
  image:
    repository: team4devops/ecommerce-payment-service
    tag: v1.0.0
  replicas: 1
productService:
  image:
    repository: team4devops/ecommerce-product-service
    tag: v1.0.0
  replicas: 2
recommendationService:
  image:
    repository: team4devops/ecommerce-recommendation-service
    tag: v1.0.0
  replicas: 1
reviewRatingService:
  image:
    repository: team4devops/ecommerce-review-rating-service
    tag: v1.0.0
  replicas: 1
searchService:
  image:
    repository: team4devops/ecommerce-search-service
    tag: v1.0.0
  replicas: 1
shippingService:
  image:
    repository: team4devops/ecommerce-shipping-service
    tag: v1.0.0
  replicas: 1
userService:
  image:
    repository: team4devops/ecommerce-user-service
    tag: v1.0.0
  replicas: 1
wishlistService:
  image:
    repository: team4devops/ecommerce-wishlist-service
    tag: v1.0.0
  replicas: 1
